# Bridge file its always used because it creates the bridges between the core RML (details_jenkins) with mlflow
# NO BRIDGES NEEDED FOR NOW (details_jenkins) does not link with mlflow for now
bridges: