client:
  apikey: "password"
db:
  host: localhost
  port: 5432
  name: provenance
  username: postgres
  password: postgres
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${db.host}:${db.port}/${db.name}"
    username: ${db.username}
    password: ${db.password}
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048
logging:
  level:
    org.springframework.boot.context.config: DEBUG
jenkins:
  host: https://jenkins.services.ai4os.eu
mlflow:
  ai4eosc:
    host: https://mlflow.cloud.ai4eosc.eu
  imagine:
    host: http://mlflow.cloud.imagine-ai.eu/
nomad:
  host: https://api.cloud.ai4eosc.eu
  fullInfo: true
  credentials:
    token: 2f94d8f880ac44de741ec4806bedf11a53e79844a22b3f0dc8ab4db22d350cfb
    vo: ifca
