name: Build image

# Note:
# HARBOR_URL, HARBOR_USERNAME, HARBOR_TOKEN are defined at the organization level

on: workflow_dispatch

jobs:
  call-compile:
    uses: ./.github/workflows/compile-skip-tests.yml
  
  build:    
    needs: call-compile
    runs-on: ubuntu-latest

    steps:       
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_URL  }}
          username: ${{ vars.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/prov-api:latest
          file: ./Dockerfile